# Generated by Django 2.2.2 on 2022-08-22 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_store', '0003_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
